
name: Limetest
on: [push]
jobs:
  test-cli:
    runs-on:
      - arc-runner-set
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chrome
      
      - name: Install @limetest/limetest
        run: npm install @limetest/limetest@latest
      
      - name: Run Limetest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npx limetest